class ResortPage {
  get heading() {
    return $("h1");
  }

  get form() {
    return $('[role="form"][aria-label="Check Rates and Availability"]');
  }

  get dates() {
    return this.form.$("#datefield-id");
  }

  async selectDate(label) {
    const day = $(`button[aria-label$="${label}"]`);

    // Bounded for this scenario's 30-day lead time and two-night stay.
    // Dates more than three month advances away are not supported here.
    const maximumMonthAdvances = 3;

    for (let month = 0; month < maximumMonthAdvances; month++) {
      const targetDateIsVisible = await day.isDisplayed();
      // Check if the target date is visible in the current month view
      if (targetDateIsVisible) {
        break;
        // If the target date is visible, exit the loop
      }

      await $('button[aria-label="Next month"]').click();
      // If the target date is not visible, click the "Next month" button to advance the calendar view
    }

    await day.waitForEnabled({ timeout: 30000 });
    // Wait for the target date to be enabled (clickable) before clicking it
    await day.click();
  }

  // Set the stay dates by selecting the arrival and departure dates in the date picker
  // It receives the stay object generated by futureStay() in booking.data.js.
  // stay.arrivalLabel, stay.departureLabel
  async setStay(stay) {
    await this.form.waitForDisplayed({ timeout: 30000 });
    await this.dates.click();

    await this.selectDate(stay.arrivalLabel);
    await this.selectDate(stay.departureLabel);

    await $("button=Apply").click();
  }

  async checkRates() {
    await this.form.$("button=Check Rates").click();
  }
}

// Create an instance of the ResortPage class and export it as the default export
export default new ResortPage();

// Getters are used here as some elements are reused acorss multiple methods.
// Form is used in both setStay() and checkRates().

/*
Here, we separate selectDate() from setStay() to allow for more flexible date selection in the future.
The main reason for separating them is reuse.
Without selectDate(), we'd need to duplicate the calendar logic for arrival and departure.

Conceptually:
selectDate()
= "How do I select one date?"

setStay()
= "How do I use that capability to configure a hotel stay?"

Hence,
I separated the single-date calendar logic into selectDate() because 
both arrival and departure need the same month-navigation and enabled-state handling. 
setStay() then orchestrates the higher-level flow by opening the calendar, selecting both dates, and applying them.
*/
